FROM python
WORKDIR /app/
COPY ./requirements.txt /app/

#ENV TZ=America/Sao_Paulo
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN python -m pip install --upgrade pip \
 && pip install -r requirements.txt


ENTRYPOINT ["sh", "entrypoint.sh"]
