FROM 192.168.1.14:5000/library/python:3.8-alpine3.13
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/

RUN apk add --no-cache gcc \
 && apk add --no-cache musl-dev \
 && apk add --no-cache g++ \
 && apk add --no-cache build-base \
 && apk add --no-cache libressl-dev \
 && apk add --no-cache libffi-dev \
 && apk add --no-cache libxslt-dev \
 && apk add python3-dev openssl-dev cargo

RUN python -m pip install --upgrade pip \
 && pip install -r requirements.txt


ENTRYPOINT ["tail", "-f","/dev/null"]